### PR TITLE
Fix the preimage display at height=0

### LINKED ISSUE #167: Off by one error in pre-image handling
Currently, showing the validators at `height == 0` (or their enrollment) shows `preimage` as `null` and `distance` as `nan`.
The distance should be `0` and the pre-image should be the `random_seed`.

### PR DESCRIPTION
**Pull request by TrustHenry**
At height=0, the distance = 0 and the `preimage` is displayed as `randomHash`

The enrollments of the Genesis block starts with zero avail_height.

Fixed #167

### CODE REVIEW

File: src/Stoa.ts [hunk 1]
```diff
@@ -173,8 +173,17 @@ class Stoa extends WebService
...
+                        if (target_height == new Height(0n))
+                        {
+                            preimage_distance = 0;
+                            result_preimage_hash = row.random_seed;
+                        }
+                        else
+                        {
+                            preimage_distance = NaN;
+                            result_preimage_hash = Hash.NULL;
+                        }
```
Comment (Geod24) [inline src/Stoa.ts]: Why is it special-casing the genesis block ? Any enrollment contains the preimage at distance 0.

Comment (TrustHenry) [reply src/Stoa.ts]: That's right. I'm testing it now.

Comment (TrustHenry) [reply src/Stoa.ts]: I fixed it

File: src/Stoa.ts [hunk 2]
```diff
@@ -173,8 +173,16 @@ class Stoa extends WebService
                     }
                     else
                     {
-                        preimage_distance = NaN;
-                        result_preimage_hash = Hash.NULL;
+                        if (target_height == new Height(row.enrolled_at))
+                        {
+                            preimage_distance = 0;
```
Comment (TrustHenry) [inline src/Stoa.ts:188]: How does the re-enrollment change the preimage distance?
I'll have to find out.

**Comment by AndrejMitrovic** [comment]
Why is the code for `getValidator` and `getValidators` copy pasted?

File: src/Stoa.ts (hunk 2 above)
Comment (AndrejMitrovic) [reply src/Stoa.ts:188]: Re-enrolling sets the distance to zero.

**Comment by TrustHenry** [comment]
> Why is the code for `getValidator` and `getValidators` copy pasted?

I didn't want to use the cloned code either, 
but I haven't moved the business code yet.
I'll refactoring.

**Comment by AndrejMitrovic** [comment]
Alright, it would be good to refactor it.

**Comment by TrustHenry** [comment]
> Alright, it would be good to refactor it.

Related to #189

File: src/Stoa.ts [hunk 3]
```diff
@@ -180,8 +180,16 @@ class Stoa extends WebService
                     }
                     else
                     {
-                        preimage_distance = NaN;
-                        result_preimage_hash = Hash.NULL;
+                        if (target_height == new Height(row.enrolled_at))
```
Comment (MichaelKim20) [inline src/Stoa.ts]: It's not a deep comparison, so we'd better modify it like this.
```suggestion
                        if (target_height.value == row.enrolled_at)
```
I got the following result from the code below. 
```
        let h1 = new Height(100n);
        let h2 = new Height(100n);
        console.log(h1 == h2); // false
```

**Comment by MichaelKim20** [comment]
Is it normal that there is no data when API 'GET /validators/' is called with a height value 0?
The enrollment data for the genesis block has an enrolled_at of 0.

**Comment by TrustHenry** [comment]
> Is it normal that there is no data when API 'GET /validators/' is called with a height value 0?
> The enrollment data for the genesis block has an enrolled_at of 0.

I just applied the comment above, so it should work.

**Comment by TrustHenry** [comment]
It works well.

File: tests/Utils.ts [hunk 4]
```diff
@@ -37,14 +37,14 @@ export const sample_data =
 export const sample_preImageInfo =
     {
         "enroll_key": "0x46883e83778481d640a95fcffd6e1a1b6defeaac5a8001cd3f99e17576b809c7e9bc7a44c3917806765a5ff997366e217ff54cd4da09c0c51dc339c47052a3ac",
-        "hash": "0x0a8201f9f5096e1ce8e8de4147694940a57a188b78293a55144fc8777a774f2349b3a910fb1fb208514fb16deaf49eb05882cdb6796a81f913c6daac3eb74328",
+        "hash": "0x1bb929c4098dc30882a26afaa2ab3f338e7f381bea11961588c96fdf6c08712056329ceaa6b1eba5e97251c0220ed38ce119071cad612c875f764d9665916840",
```
Comment (MichaelKim20) [inline tests/Utils.ts]:
```suggestion
        "hash": "0x790ab7c8f8ddbf012561e70c944c1835fd1a873ca55c973c828164906f8b35b924df7bddcafade688ad92cfb4414b2cf69a02d115dc214bbd00d82167f645e7e",
```

File: tests/Utils.ts [hunk 5]
```diff
@@ -37,14 +37,14 @@ export const sample_data =
...
         "distance": 6
     };
 
 export const sample_reEnroll_preImageInfo =
     {
         "enroll_key": "0x46883e83778481d640a95fcffd6e1a1b6defeaac5a8001cd3f99e17576b809c7e9bc7a44c3917806765a5ff997366e217ff54cd4da09c0c51dc339c47052a3ac",
-        "hash": "0x25677ee5a05590d68276d1967cbe37e3cf3e731502afd043fafc82b0181cd120cef6272e5aea2dafaca0236a4ce7c1edd4fe21ae770930a8e206bd7080066a4c",
+        "hash": "0x67703b91cc77c0ac403e19b38fecd3b6474d03f309f89ff3b00fa3f6cc9b377a2804d7dd9a19c6365bd2068fef1ab5a801f1b9530bad4d0ce1fb872230cd9508",
```
Comment (MichaelKim20) [inline tests/Utils.ts]:
```suggestion
        "hash": "0xe51e1cc8dfdcdcd02586c9648c6977504eade2dffc8f3289e7ae7e501c2879f99af6a199ccad499be02a66d409ca4ab51b35f1c3a06a82464ce4efcfeb3ade33",
```

**Review by MichaelKim20 — APPROVED** [review]
I checked that the pre-image becomes random-seed when the distance is zero in each cycle.
LGTM
