### PR TITLE
Change error status code for Get request

### LINKED ISSUE #139: No error code returned on wrong height
Currently, starting a Stoa without Agora, and doing a `curl`, a.k.a:
```shell
$ curl http://127.0.0.1:4242/validators
```

I get an empty response on the query side, but can see that the request was processed:
```
[Stoa] 2020-10-23T04:15:10.214Z http GET /validators
```

Returning no data and no error code is surprising to the user, which is likely to always expect something.
While a bare `/validators` call should always succeed (currently fails because of #137), the following might not:
```
$ curl http://127.0.0.1:4242/validators?height=4242424242
```
And should definitely return an error code. This obviously apply to all endpoints.

### PR DESCRIPTION
**Pull request by TrustHenry**
The GET /validators call should always be successful,
but Stoa cannot be serviced if Stoa is listening to the block or if there is a problem with the DB.
The GET /validator may request an incorrect height.
In this case, return the 400 status code and respond that there is no data.

Fixed #139

### CODE REVIEW

File: src/Stoa.ts [hunk 1]
```diff
@@ -232,7 +231,7 @@ class Stoa extends WebService
                 // Nothing to show
                 if (!rows.length)
                 {
-                    res.status(204).send();
+                    res.status(400).send("The validator data not found.");
```
Comment (MichaelKim20) [inline src/Stoa.ts]: How about adding `address`?

Comment (TrustHenry) [reply src/Stoa.ts]: I don't know what it means. Give me a suggestion.

File: src/Stoa.ts [hunk 2]
```diff
@@ -145,7 +144,8 @@ class Stoa extends WebService
                 // Nothing found
                 if (!rows.length)
                 {
-                    res.status(204).send();
+                    // Service Unavailable
+                    res.status(503).send("Stoa is currently unavailable.");
```
Comment (MichaelKim20) [inline src/Stoa.ts]: How about this phrase?
`No validator exists for block height.`

Comment (MichaelKim20) [reply src/Stoa.ts]: It would be nice if the block height was also displayed.

File: src/Stoa.ts (hunk 1 above)
Comment (MichaelKim20) [reply src/Stoa.ts]: `The validator data not found. (${address})`

Comment (MichaelKim20) [reply src/Stoa.ts]: I think this would be better.
`The validator data not found. (address: ${address}, height: ${height})`

File: src/Stoa.ts (hunk 2 above)
Comment (TrustHenry) [reply src/Stoa.ts]: Block height is optional for parameters.
Also, the `/validators` service should always be serviceable. 
The lack of data can mean that the Stoa is preparing or the DB is empty.

File: src/Stoa.ts (hunk 1 above)
Comment (TrustHenry) [reply src/Stoa.ts]: The requester will of course know the value of the parameter.
I don't think it's a bad idea to mark it.

File: src/Stoa.ts (hunk 2 above)
Comment (TrustHenry) [reply src/Stoa.ts]: However, this may require a response to an incorrect request height.

**Review by MichaelKim20 — APPROVED** [review]
LGTM
