### PR TITLE
Apply mysql connection pool

### LINKED ISSUE #366: The connection method of mysql DB needs to be improved.
Currently, DB Connection is a single connection that can cause delays in handling traffic in competitive situations or user spikes.
Also, there is no attempt to reconnect in case of connection failure.

A connection pool is available.

### LINKED ISSUE #403: Approximately 12 hours after running the stoa, the DB connection is lost and the process is forced to terminate.
Below is the execution log.
```
[Stoa] 2021-07-27T16:33:45.363Z info Emitted Updated BOA stats:  [object Object]
Warning: got packets out of order. Expected 2 but received 0
[Stoa] 2021-07-27T16:52:40.158Z error uncaughtException: Unexpected packet while no commands in the queue
Error: Unexpected packet while no commands in the queue
    at Connection.protocolError (/stoa/bin/node_modules/mysql2/lib/connection.js:371:17)
    at Connection.handlePacket (/stoa/bin/node_modules/mysql2/lib/connection.js:418:12)
    at PacketParser.onPacket (/stoa/bin/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/stoa/bin/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/stoa/bin/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
Warning: got packets out of order. Expected 3 but received 0
[Stoa] 2021-07-27T16:52:40.163Z error uncaughtException: Connection lost: The server closed the connection.
Error: Connection lost: The server closed the connection.
    at Socket.<anonymous> (/stoa/bin/node_modules/mysql2/lib/connection.js:91:31)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at TCP.<anonymous> (net.js:673:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stoa@0.0.0 start: `cross-env NODE_ENV=production ts-node src/main.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stoa@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-27T16_52_43_179Z-debug.log

> stoa@0.0.0 start /stoa/bin
> cross-env NODE_ENV=production ts-node src/main.ts

[Stoa] 2021-07-27T23:45:41.914Z info Agora endpoint: http://node-2:2826

```

### PR DESCRIPTION
**Pull request by TrustHenry**
Connection pools help reduce the time spent connecting to the MySQL server by reusing a previous connection,
leaving them open instead of closing when you are done with them.
This improves the latency of queries as you avoid all of the overhead
that comes with establishing a new connection.
The connection can now be pulled out of the pool and used to 
create a new connection or to use the created connection.

### CODE REVIEW

File: src/modules/storage/LedgerStorage.ts [hunk 1]
```diff
@@ -349,14 +355,20 @@ export class LedgerStorage extends Storages {
     /**
      * Puts a block to database
      * @param block a block data
+     * @param conn Use this if it are providing a db connection.
```
Comment (MichaelKim20) [inline src/modules/storage/LedgerStorage.ts]: This is an unused parameter. Parameters used by functions that exist inside. Therefore, I would like to remove this.

File: src/modules/storage/Storages.ts [hunk 2]
```diff
@@ -66,6 +62,22 @@ export class Storages {
...
 
+    /**
+     * Returns the DB connection of the Connection Pool.
+     * @returns Returns the Promise. If it is finished successfully the `.then`
+     * of the returned Promise is called and if an error occurs the `.catch`
+     * is called with an error.
+     */
+
+    public getConnection(): Promise<any> {
+        return new Promise<any>((resolve, reject) => {
```
Comment (MichaelKim20) [inline src/modules/storage/Storages.ts]:
```suggestion
    public getConnection(): Promise<mysql.PoolConnection> {
        return new Promise<mysql.PoolConnection>((resolve, reject) => {
```

File: src/modules/storage/LedgerStorage.ts [hunk 3]
```diff
@@ -73,12 +73,18 @@ export class LedgerStorage extends Storages {
...
+                    result._transaction_pool = new TransactionPool(result);
+                    result
+                        .getConnection()
+                        .then(async (conn) => {
+                            await result.transaction_pool.loadSpenderList(conn);
+                            return resolve(result);
+                        })
+                        .catch((error) => {
+                            reject(error);
+                        });
```
Comment (MichaelKim20) [inline src/modules/storage/LedgerStorage.ts]:
```suggestion
                 await result.transaction_pool.loadSpenderList();
                 return resolve(result);
```

File: src/modules/storage/TransactionPool.ts [hunk 4]
```diff
@@ -101,9 +110,9 @@ export class TransactionPool {
      * Load transactions and make the spender list
      * @param connection MySQL connection
      */
-    public async loadSpenderList(connection: mysql.Connection) {
+    public async loadSpenderList(conn?: mysql.PoolConnection) {
```
Comment (MichaelKim20) [inline src/modules/storage/TransactionPool.ts]:
```suggestion
    public async loadSpenderList() {
```

File: src/modules/storage/TransactionPool.ts [hunk 5]
```diff
@@ -101,9 +110,9 @@ export class TransactionPool {
...
         this.spenders.clear();
-        const rows = await this.query(connection, "SELECT `key`, `val` FROM tx_pool;", []);
+        const rows = await this.storage.query("SELECT `key`, `val` FROM tx_pool;", [], conn);
```
Comment (MichaelKim20) [inline src/modules/storage/TransactionPool.ts]:
```suggestion
        const rows = await this.storage.query("SELECT `key`, `val` FROM tx_pool;", []);
```

**Review by MichaelKim20 — CHANGES_REQUESTED** [review]
It's very good to modify a few minor things.

**Comment by TrustHenry** [comment]
@MichaelKim20 Thank you for the reviews.
 I applied the suggestions now.

File: src/modules/storage/TransactionPool.ts [hunk 6]
```diff
@@ -101,9 +110,9 @@ export class TransactionPool {
      * Load transactions and make the spender list
      * @param connection MySQL connection
```
Comment (MichaelKim20) [inline src/modules/storage/TransactionPool.ts]: Please delete this line.

**Review by MichaelKim20 — APPROVED** [review]
Good Work

File: src/modules/storage/TransactionPool.ts (hunk 6 above)
Comment (TrustHenry) [reply src/modules/storage/TransactionPool.ts]: I remove it.
